Added style definitions for the Apply form
trabian/demo-application pull request #10
Opened 2017-06-14 19:28 UTC by Ameobea

2017-06-14 19:36 UTC, jimmyhmiller requested changes

2017-06-14 19:36 UTC, jimmyhmiller commented on src/components/apply/formStyles.js
> +    validate={applyValidators(required ? [requiredValidator, ...validators] : validators)}
`requiredValidator` doesn't exist

2017-06-14 19:36 UTC, jimmyhmiller commented on src/components/apply/formStyles.js
> +const applyValidators = validators => (input, lastInput) => {
Help me understand this method. Why are we applying all validators and then finding the first?

2017-06-14 19:36 UTC, jimmyhmiller commented on src/components/apply/formStyles.js
> +    validate={applyValidators(required ? [requiredValidator, ...validators] : validators)}
Why did you choose to do validations at the field level rather than the form level?

2017-06-14 19:36 UTC, jimmyhmiller commented on src/components/apply/formStyles.js
> +const labelStyle = label => ({
Why make this a function of label? Do you expect the styles to changed based on the label text?

2017-06-14 20:31 UTC, marsha88 commented on src/components/apply/formStyles.js
> +const labelStyle = label => ({
Fixed

2017-06-15 14:14 UTC, jimmyhmiller approved these changes

2017-06-15 14:15 UTC, merged